### ISSUE TITLE
pop vs pop_without_blocking

### ISSUE THREAD

**Issue by mroe1234** [mschneider82/logstash-input-nsq#5]
The readme states that pop blocks, however, it looks like you created a second function "pop_without_blocking" but aren't using it.  It looks like switching to the nonblocking will allow logstash to restart/reload properly.  I've included the snippet from consumer.rb for reference below.

 # pop the next message off the queue
    def pop
      @messages.pop
    end

    # By default, if the internal queue is empty, pop will block until
    # a new message comes in.
    #
    # Calling this method won't block. If there are no messages, it just
    # returns nil.
    def pop_without_blocking
      @messages.pop(true)
    rescue ThreadError
      # When the Queue is empty calling `Queue#pop(true)` will raise a ThreadError
      nil
    end

**Comment by mschneider82** [comment]
Hi, yes `pop_without_blocking` exists in the used `nsq-ruby` library. But its not implemented in my plugin. If there is enogth traffic on the input queue the exit is working fine with blocking.

If you dont have traffic on the queue, you can even hard kill logstash (e..g with systemd or upstart), you dont have to fear to loose messages when it`s blocked.

Using `pop_without_blocking` with sleep & retry just slow down processing and produces CPU.
